[package]
name = "rbckp"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
blake3 = "1.8.3"
clap = { version = "4.5.57", features = ["derive"] }
config = "0.15.19"
log = "0.4.29"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
simplelog = "0.12.2"
